# Generated by Django 3.2.5 on 2021-07-03 12:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None)),
                ('published_date', models.DateField(null=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None)),
                ('average_rating', models.FloatField(null=True)),
                ('ratings_count', models.PositiveIntegerField(null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=256)),
            ],
        ),
    ]
